server:
  port: 8080

logging:
  structured:
    format:
      console: logstash

spring:
  application:
    name: gateway-service
  threads:
    virtual:
      enabled: true

info:
  commit: ${GIT_SHA:unknown}

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  opentelemetry:
    resource-attributes:
      "service.version": "@project.version@"
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:http://localhost:4318/v1/traces}

account-service:
  base-url: ${ACCOUNT_SERVICE_URL:http://localhost:8081}

transfer-service:
  base-url: ${TRANSFER_SERVICE_URL:http://localhost:8082}

keycloak:
  issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/showcase}
  jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8180/realms/showcase/protocol/openid-connect/certs}
